<?php

    /*!
     * ifsoft.co.uk
     *
     * http://ifsoft.com.ua, http://ifsoft.co.uk
     * raccoonsquare@gmail.com
     *
     * Copyright 2012-2019 Demyanchuk Dmitry (raccoonsquare@gmail.com)
     */

$C['APP_TYPE_ALL'] = -1;
$C['APP_TYPE_MANAGER'] = 0;
$C['APP_TYPE_WEB'] = 1;
$C['APP_TYPE_ANDROID'] = 2;
$C['APP_TYPE_IOS'] = 3;

$C['GCM_NOTIFY_VIDEO_COMMENT_REPLY'] = 21;
$C['GCM_NOTIFY_VIDEO_COMMENT'] = 22;
$C['GCM_NOTIFY_VIDEO_LIKE'] = 23;

$C['GCM_NOTIFY_REFERRAL'] = 24;

$C['GCM_NOTIFY_MATCH'] = 25;

$C['GCM_NOTIFY_TYPING_START'] = 27;
$C['GCM_NOTIFY_TYPING_END'] = 28;

$C['GCM_NOTIFY_MEDIA_APPROVE'] = 1001;
$C['GCM_NOTIFY_MEDIA_REJECT'] = 1002;
$C['GCM_NOTIFY_PROFILE_PHOTO_APPROVE'] = 1003;
$C['GCM_NOTIFY_PROFILE_PHOTO_REJECT'] = 1004;
$C['GCM_NOTIFY_ACCOUNT_APPROVE'] = 1005;
$C['GCM_NOTIFY_ACCOUNT_REJECT'] = 1006;
$C['GCM_NOTIFY_PROFILE_COVER_APPROVE'] = 1007;
$C['GCM_NOTIFY_PROFILE_COVER_REJECT'] = 1008;

$C['NOTIFY_TYPE_MEDIA_APPROVE'] = 10;
$C['NOTIFY_TYPE_MEDIA_REJECT'] = 11;
$C['NOTIFY_TYPE_PROFILE_PHOTO_APPROVE'] = 12;
$C['NOTIFY_TYPE_PROFILE_PHOTO_REJECT'] = 13;
$C['NOTIFY_TYPE_ACCOUNT_APPROVE'] = 14;
$C['NOTIFY_TYPE_ACCOUNT_REJECT'] = 15;
$C['NOTIFY_TYPE_PROFILE_COVER_APPROVE'] = 16;
$C['NOTIFY_TYPE_PROFILE_COVER_REJECT'] = 17;

$C['IMAGE_TYPE_PROFILE_PHOTO'] = 0;
$C['IMAGE_TYPE_PROFILE_COVER'] = 1;